version: '3.8'
services:

   # Database Server
  mysql:
      image: mysql:8.0
      restart: always
      ports:
          -   3306:3306
     
      environment:
          - MYSQL_DATABASE=homestead
          - MYSQL_USER=homestead
          - MYSQL_PASSWORD=secret
          - MYSQL_ROOT_PASSWORD=secret
      healthcheck:
             test: ["CMD-SHELL", 'mysqladmin ping']
             interval: 10s
             timeout: 2s
             retries: 10
      volumes:
            - ./data:/var/lib/mysql
      
      networks:

          - app

  backend:
    
    build:
    
      context: ./backend
      
      dockerfile: Dockerfile
    ports:

      - 8000:8000
    
    volumes:
        
      - ./backend:/app/backend

    depends_on:

      - mysql
     
               #condition: service_healthy
    links:
      - mysql

    networks:
      - app
  
  
  frontend:
    build:
      context: ./Appfrontend
      dockerfile: Dockerfile
    
    tty: true
    
    ports:

      - 8080:8080
    
    volumes:
        
      - ./Appfrontend:/app/Appfrontend

    depends_on:
      - mysql
      - backend
  


volumes:
    db-data: ~
    db-phpmyadmin: ~

networks:

  app:

    driver: bridge
